/** Persian names of the tables a backup file contains, for the "this file has…" summaries. */
export const TABLE_LABELS_FA: Record<string, string> = {
  User: "کاربر",
  Settings: "تنظیمات",
  Project: "پروژه",
  Category: "دسته‌بندی",
  Task: "کار",
  Habit: "عادت",
  Activity: "فعالیت",
  HabitCheckIn: "چک‌این عادت",
  TimeEntry: "بازه زمانی",
  FinanceAccount: "حساب مالی",
  Asset: "دارایی",
  AssetTransaction: "تراکنش دارایی",
  InstallmentPlan: "طرح قسط",
  Installment: "قسط",
  Event: "رویداد",
  EventCompletion: "تکمیل رویداد",
  VirtualAssetEntry: "دارایی مجازی",
  Transaction: "تراکنش مالی",
  Reminder: "یادآور",
  DailyNote: "نوت روزانه",
  CapitalSnapshot: "تاریخچه سرمایه",
  AuditLog: "سابقه فعالیت",
  Notification: "اعلان",
};
