// Finds transactions that quietly repeat every month — rent, a subscription, anything typed in
// by hand often enough that the app can tell without being told. "Same category, similar amount,
// at least two of the last few months" is the whole signal: no title-matching (people don't type
// the same words twice — "قبض اینترنت شهریور" vs "...مهر" — so a category is the stable anchor a
// free-typed description never is). Deliberately excludes anything already generated by something
// else (an installment payment, a task's direct cost, an event, an activity) — those are already
// structured recurrences the app knows about on their own terms; this is for the ones nobody told
// it about yet. "این هر ماه تکرار می‌شود، ثبت شود؟" — one tap logs THIS month's occurrence via the
// normal /api/transactions route; nothing here ever runs unattended or writes on its own.
export type RecurringTxnType = "INCOME" | "EXPENSE";

export interface TransactionForDetection {
  id: string;
  description: string | null;
  amount: number;
  date: Date;
  type: "INCOME" | "EXPENSE" | "TRANSFER";
  categoryId: string | null;
  accountId: string;
  installmentId?: string | null;
  taskId?: string | null;
  eventId?: string | null;
  activityId?: string | null;
}

export interface RecurringCandidate {
  categoryId: string;
  /** The most recent occurrence's own description — never invented. */
  title: string;
  type: RecurringTxnType;
  /** For the one-tap "ثبت کن" action — the account the last occurrence was logged against. */
  accountId: string;
  averageAmount: number;
  /** The actual amount logged THIS calendar month against this pattern, or null if not yet. */
  thisMonthAmount: number | null;
  /** How many of the last LOOKBACK_MONTHS months had a matching entry. */
  occurrences: number;
}

const LOOKBACK_MONTHS = 4;
const AMOUNT_TOLERANCE = 0.15; // ±15% of the cluster's median counts as "the same bill"
const MIN_OCCURRENCES = 2;

function monthKey(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

/** One candidate per (category, amount-cluster) — a category with two genuinely different
 * recurring amounts (rent AND a much smaller recurring category fee, say) yields two candidates,
 * not one blurred average. */
export function detectRecurringTransactions(transactions: TransactionForDetection[], now: Date = new Date()): RecurringCandidate[] {
  const cutoff = new Date(now.getFullYear(), now.getMonth() - LOOKBACK_MONTHS + 1, 1);
  const currentMonth = monthKey(now);

  const eligible = transactions.filter(
    (t) =>
      t.type !== "TRANSFER" &&
      t.categoryId &&
      !t.installmentId &&
      !t.taskId &&
      !t.eventId &&
      !t.activityId &&
      t.date >= cutoff
  );

  const byCategory = new Map<string, TransactionForDetection[]>();
  for (const t of eligible) {
    const list = byCategory.get(t.categoryId!) ?? [];
    list.push(t);
    byCategory.set(t.categoryId!, list);
  }

  const candidates: RecurringCandidate[] = [];

  for (const [categoryId, txs] of byCategory) {
    // At most one entry per month per category (the latest that month) — several bills the same
    // month against the same category would otherwise inflate the occurrence count.
    const byMonth = new Map<string, TransactionForDetection>();
    for (const t of [...txs].sort((a, b) => a.date.getTime() - b.date.getTime())) {
      byMonth.set(monthKey(t.date), t);
    }
    const monthly = Array.from(byMonth.values());
    if (monthly.length < MIN_OCCURRENCES) continue;

    const clusterMedian = median(monthly.map((t) => t.amount));
    const clustered = monthly.filter((t) => Math.abs(t.amount - clusterMedian) / clusterMedian <= AMOUNT_TOLERANCE);
    if (clustered.length < MIN_OCCURRENCES) continue;

    clustered.sort((a, b) => a.date.getTime() - b.date.getTime());
    const last = clustered[clustered.length - 1];
    const thisMonthEntry = clustered.find((t) => monthKey(t.date) === currentMonth);
    const averageAmount = Math.round(clustered.reduce((s, t) => s + t.amount, 0) / clustered.length);

    candidates.push({
      categoryId,
      title: last.description?.trim() || "بدون عنوان",
      type: last.type as RecurringTxnType,
      accountId: last.accountId,
      averageAmount,
      thisMonthAmount: thisMonthEntry ? thisMonthEntry.amount : null,
      occurrences: clustered.length,
    });
  }

  return candidates.sort((a, b) => b.occurrences - a.occurrences || b.averageAmount - a.averageAmount);
}

/** "این ماه X تومان صرف اشتراک‌ها شد" — the real total already logged this month against
 * recognized patterns, not a projection. 0 when nothing this month matched one yet. */
export function recurringSpendThisMonth(candidates: RecurringCandidate[]): number {
  return candidates.filter((c) => c.type === "EXPENSE" && c.thisMonthAmount != null).reduce((s, c) => s + (c.thisMonthAmount ?? 0), 0);
}
