export interface TimeCostResult {
  directCost: number;
  timeCost: number;
  realCost: number;
}

/** Time Cost = duration(hours) x hourlyValue. Rounded to the nearest Toman. */
export function computeTimeCost(durationMin: number, hourlyValue: number): number {
  return Math.round((durationMin / 60) * hourlyValue);
}

/** Real Cost = Direct Cost + Time Cost. */
export function computeRealCost(durationMin: number, directCost: number, hourlyValue: number): TimeCostResult {
  const timeCost = computeTimeCost(durationMin, hourlyValue);
  return {
    directCost,
    timeCost,
    realCost: directCost + timeCost,
  };
}

/** Virtual asset value generated by time spent in a category with a defined per-hour value. */
export function computeVirtualAssetValue(durationMin: number, valuePerHour: number): number {
  return Math.round((durationMin / 60) * valuePerHour);
}
