// Builds the two reference documents in doc/logging/ straight from the registries, so they can
// never drift from the code: a test regenerates them and fails if the checked-in files differ.
// Regenerate with:  npx tsx scripts/logs/generate-docs.ts
import { ERROR_CODES, syncErrorCode, type ErrorCode, type SyncErrorKind } from "./core/errorCodes";
import { DOMAINS, EVENTS, EVENT_NAMES, MODULE_OF_DOMAIN, OPERATIONS, type Domain } from "./core/events";

export interface SourceFile {
  /** Repo-relative path with forward slashes. */
  path: string;
  text: string;
}

/** Files whose mention of an event name or code is the definition/documentation, not a use. */
function isUsageFile(file: SourceFile): boolean {
  if (/\.test\.tsx?$/.test(file.path)) return false;
  if (file.path.startsWith("src/testing/")) return false;
  return !/^src\/lib\/observability\/(core\/(events|errorCodes)\.ts|docsGenerator\.ts|index\.ts)$/.test(file.path);
}

/**
 * Codes that are never written as a literal because a helper picks them: calling the helper is what
 * emits them. (classifyError is called by the logger itself for every logged error.)
 */
const SYNC_KINDS: SyncErrorKind[] = ["network", "auth", "too-large", "server", "unknown"];
const CODES_VIA_HELPER: Array<{ call: string; codes: string[] }> = [
  { call: "syncErrorCode(", codes: SYNC_KINDS.map((kind) => syncErrorCode(kind)) },
  { call: "classifyError(", codes: ["VAL-001", "AUTH-003", "DB-001", "DB-002", "DB-004", "DB-005", "DB-006", "DB-007"] },
];

/** TASK_CREATE, EXPENSE_CREATE, TIME_TIMER_STOP … — the base of an operation's three events. */
const OPERATION_BASES: ReadonlySet<string> = new Set(Object.entries(OPERATIONS).flatMap(([domain, actions]) => (actions as readonly string[]).map((action) => `${domain}_${action}`)));

/**
 * withTransaction({ operation: "TASK_CREATE" }) writes TASK_CREATE_FAILED when it rolls back, without that
 * name ever appearing as a literal: an operation named on a line that says `operation:` counts as emitting its FAILED event.
 */
function operationsNamedIn(text: string): string[] {
  const named: string[] = [];
  for (const line of text.split("\n")) {
    if (!line.includes("operation:")) continue;
    for (const match of line.matchAll(/["'`]([A-Z]+(?:_[A-Z]+)+)["'`]/g)) if (OPERATION_BASES.has(match[1])) named.push(match[1]);
  }
  return named;
}

/** Which registered event names / error codes application code writes (as literals, or through a code-picking helper). */
export function findUsages(files: SourceFile[]): { events: Set<string>; codes: Set<string> } {
  const events = new Set<string>();
  const codes = new Set<string>();
  const eventPattern = new RegExp(`["'\`](${EVENT_NAMES.join("|")})["'\`]`, "g");
  const codePattern = /["'`]([A-Z]+-\d{3})["'`]/g;
  for (const file of files.filter(isUsageFile)) {
    for (const match of file.text.matchAll(eventPattern)) events.add(match[1]);
    for (const base of operationsNamedIn(file.text)) events.add(`${base}_FAILED`);
    for (const match of file.text.matchAll(codePattern)) if (match[1] in ERROR_CODES) codes.add(match[1]);
    for (const helper of CODES_VIA_HELPER) if (file.text.includes(helper.call)) for (const code of helper.codes) codes.add(code);
  }
  return { events, codes };
}

const HEADER = "<!-- Generated by scripts/logs/generate-docs.ts from src/lib/observability — do not edit by hand. A test fails when this file is stale. -->";

function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

export function renderEventsDoc(usedEvents: Set<string>): string {
  const lines: string[] = [
    HEADER,
    "",
    "# Event catalogue",
    "",
    "Every event a log call may use. Names are `DOMAIN_ACTION_RESULT`: English, constant, machine-readable and independent of the message text. The TypeScript type `EventName` is derived from the same tables, so an event that is not listed here does not compile.",
    "",
    "- **Level** is the default severity; a call site may pick another (a sync that fails because the phone is offline is a `WARN`, not an `ERROR`).",
    "- **Flags:** `protected` — never removed by sampling or dropped by a full queue in favour of a lesser record; `security` — an authentication/authorisation event (implies protected); `high-volume` — fires per request or per tick, the only kind of `INFO` sampling may thin.",
    "- **Emitted** — `yes` when application code already writes it; otherwise the event is *reserved* for a later phase (see architecture.md).",
    "- Operations (`*_STARTED` / `*_SUCCESS` / `*_FAILED`) are generated: `STARTED` is `DEBUG`, `SUCCESS` is `INFO`, `FAILED` is `ERROR` and protected. `SUCCESS` is only ever logged after the work — including its database commit — has finished.",
    "",
    `${EVENT_NAMES.length} events in ${DOMAINS.length} domains.`,
    "",
  ];

  for (const domain of DOMAINS as readonly Domain[]) {
    const names = EVENT_NAMES.filter((name) => EVENTS[name].domain === domain).sort();
    if (names.length === 0) continue;
    lines.push(`## ${domain}`, "", `Default module: \`${MODULE_OF_DOMAIN[domain]}\``, "", "| Event | Level | Flags | Emitted | Description |", "| --- | --- | --- | --- | --- |");
    for (const name of names) {
      const meta = EVENTS[name];
      const flags = [meta.security ? "security" : meta.protected ? "protected" : "", meta.highVolume ? "high-volume" : ""].filter(Boolean).join(", ");
      lines.push(`| \`${name}\` | ${meta.level} | ${flags || "—"} | ${usedEvents.has(name) ? "yes" : "reserved"} | ${cell(meta.description)} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

export function renderErrorCodesDoc(usedCodes: Set<string>): string {
  const lines: string[] = [
    HEADER,
    "",
    "# Error codes",
    "",
    "`DOMAIN-NNN`, independent of the message a person sees: a code never changes when the Persian text does, so tickets, dashboards and alerts can rely on it. Add new codes at the end of a domain's range; never renumber or reuse one.",
    "",
    "| Code | Name | HTTP | Retryable | Emitted | Description |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const code of Object.keys(ERROR_CODES) as ErrorCode[]) {
    const meta = ERROR_CODES[code];
    const status = "httpStatus" in meta ? String(meta.httpStatus) : "—";
    lines.push(`| \`${code}\` | ${meta.name} | ${status} | ${meta.retryable ? "yes" : "no"} | ${usedCodes.has(code) ? "yes" : "reserved"} | ${cell(meta.description)} |`);
  }
  return `${lines.join("\n")}\n`;
}
