// Regenerates src/local/generatedSchema.ts from prisma/migrations/*/migration.sql.
//
// The on-device (Capacitor/Android) SQLite database can't run Prisma Client, so it can't
// apply migrations the normal way. Instead we bake the exact same DDL Prisma already
// generated for the sqlite provider into a plain JS string, replayed once by src/local/db.ts
// on first launch. This keeps prisma/schema.prisma as the single source of truth for the
// on-device schema shape — nobody hand-maintains a second copy of the table definitions.
//
// Re-run this (`npm run local:schema`) every time a new Prisma migration is added.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const migrationsDir = join(__dirname, "..", "prisma", "migrations");
const outFile = join(__dirname, "..", "src", "local", "generatedSchema.ts");

const folders = readdirSync(migrationsDir, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort(); // migration folder names are timestamp-prefixed, so lexicographic sort == chronological

const migrations = folders.map((name) => ({
  name,
  sql: readFileSync(join(migrationsDir, name, "migration.sql"), "utf8"),
}));

const banner = `// AUTO-GENERATED by scripts/generate-local-schema.ts — do not edit by hand.
// Source: prisma/migrations/*/migration.sql (${folders.length} migrations, regenerate after adding a new one).
//
// Kept as one { name, sql } entry per migration (not one concatenated blob) so src/local/db.ts's
// bootstrap() can apply only the migrations a given device hasn't seen yet — a device that
// already has migrations 1..N applied and updates to a build with migration N+1 must replay only
// N+1, not re-run 1..N's CREATE TABLE statements against tables that already exist.

export const LOCAL_SCHEMA_MIGRATIONS: readonly { name: string; sql: string }[] = ${JSON.stringify(migrations, null, 2)};
`;

writeFileSync(outFile, banner, "utf8");
console.log(`Wrote ${outFile} from ${folders.length} migrations.`);
