// Regenerates src/local/generatedSchema.ts from prisma/migrations/*/migration.sql.
//
// The on-device (Capacitor/Android) SQLite database can't run Prisma Client, so it can't
// apply migrations the normal way. Instead we bake the exact same DDL Prisma already
// generated for the sqlite provider into a plain JS string, replayed once by src/local/db.ts
// on first launch. This keeps prisma/schema.prisma as the single source of truth for the
// on-device schema shape — nobody hand-maintains a second copy of the table definitions.
//
// Re-run this (`npm run local:schema`) every time a new Prisma migration is added.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const migrationsDir = join(__dirname, "..", "prisma", "migrations");
const outFile = join(__dirname, "..", "src", "local", "generatedSchema.ts");

const folders = readdirSync(migrationsDir, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort(); // migration folder names are timestamp-prefixed, so lexicographic sort == chronological

const sql = folders
  .map((folder) => readFileSync(join(migrationsDir, folder, "migration.sql"), "utf8"))
  .join("\n");

const banner = `// AUTO-GENERATED by scripts/generate-local-schema.ts — do not edit by hand.
// Source: prisma/migrations/*/migration.sql (${folders.length} migrations, regenerate after adding a new one).

export const LOCAL_SCHEMA_MIGRATIONS: readonly string[] = ${JSON.stringify(folders, null, 2)};

export const LOCAL_SCHEMA_SQL = ${JSON.stringify(sql)};
`;

writeFileSync(outFile, banner, "utf8");
console.log(`Wrote ${outFile} from ${folders.length} migrations.`);
